<?php
/**
 * Advanced Query Loop dynamic date placeholder handling.
 *
 * Replaces meta_query values with current site-local dates, allowing editors
 * to configure relative date filters without daily updates.
 */

if (!defined('ABSPATH')) { exit; }

if (!function_exists('awesome_events_aql_replace_dynamic_dates')) {
    /**
     * Filter callback for 'aql_query_vars'.
     *
     * @param array $query_args Original WP_Query args generated by the block.
     * @param array $block_query Raw block attributes for the query.
     * @param bool  $inherited   Whether the query vars were inherited.
     * @return array Modified args.
     */
    function awesome_events_aql_replace_dynamic_dates($query_args, $block_query, $inherited) {
        if (isset($query_args['meta_query']) && is_array($query_args['meta_query'])) {
            $today = current_time('Y-m-d');
            $yesterday = gmdate('Y-m-d', strtotime('-1 day', current_time('timestamp')));

            foreach ($query_args['meta_query'] as $index => $clause) {
                if (!isset($clause['value'])) {
                    continue;
                }

                if ($clause['value'] === 'todays_date') {
                    $query_args['meta_query'][$index]['value'] = $today;
                } elseif ($clause['value'] === 'today_minus_1') {
                    $query_args['meta_query'][$index]['value'] = $yesterday;
                } elseif (is_array($clause['value'])) {
                    foreach ($clause['value'] as $value_index => $value) {
                        if ($value === 'todays_date') {
                            $query_args['meta_query'][$index]['value'][$value_index] = $today;
                        } elseif ($value === 'today_minus_1') {
                            $query_args['meta_query'][$index]['value'][$value_index] = $yesterday;
                        }
                    }
                }
            }
        }

        return $query_args;
    }

    add_filter('aql_query_vars', 'awesome_events_aql_replace_dynamic_dates', 10, 3);
}